// Generated by CoffeeScript 1.7.0
print("world");

utils.print_once(1);

print(2);

warning(3);

emit_event(2);

urls.command(3);

urls.postcommand(3);

async_call_retries(4);

utils.set_time_out(4);

utils.set_interval(2);

//# sourceMappingURL=test.map
